spring:
  application:
    name: property-service
  datasource:
    url: jdbc:mysql://localhost:3306/propertydb
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      persist-authorization: true
  logging:
    level:
      org.springdoc: DEBUG
  front:
    url: http://localhost:4200

  # Spring Cloud Config Client Configuration
spring.cloud.config.uri: http://localhost:8888  # L'URL du serveur de configuration
